name: main
on:
  push:
    branches: [main,release/6.0]
  pull_request:
    branches: [main]

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          dotnet build -c Release
      - name: Install FFmpeg - linux
        run: |
          sudo apt update
          sudo apt install software-properties-common -y
          sudo add-apt-repository ppa:savoury1/ffmpeg4 -y
          sudo add-apt-repository ppa:savoury1/ffmpeg5 -y
          sudo add-apt-repository ppa:savoury1/ffmpeg6 -y
          sudo apt update
          sudo apt install ffmpeg -y
      - name: Test
        run: |
          dotnet test -c Release
  windows-latest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          dotnet build -c Release
      - name: Codegen Build & Test
        run: |
          dotnet run -c Release --project src/Sdcb.FFmpeg.AutoGen --
          dotnet build src/Sdcb.FFmpeg
      - name: Test
        run: |
          dotnet test -c Release
      - uses: actions/upload-artifact@v3
        with:
          path: |
            src/Sdcb.FFmpeg/bin/Release/*.nupkg
            src/Sdcb.FFmpeg/bin/Release/*.snupkg
          if-no-files-found: error
      - name: Publish to NuGet
        if: github.event_name == 'push'
        run: dotnet nuget push .\src\Sdcb.FFmpeg\bin\Release\*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_API_KEY}} --skip-duplicate